apiVersion: v2
name: warehouse
description: A Helm chart for prodms-warehouse microservice
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.0.0-SNAPSHOT"

dependencies:
  - name: basic
    version: 1.0.0-SNAPSHOT
    condition: basicEnabled
    repository: "https://yuryklimchuk.github.io/prodms-helm"
