apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.id }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.id }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.id }}
    spec:
      serviceAccountName: {{ .Values.app.id }}-sa
      containers:
        - name: {{ .Values.app.id }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.tag }}:{{ .Values.image.version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ .Values.app.id }}-env-cm

