apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.id }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.app.id }}
