apiVersion: v2
name: apps-facade
description: A Helm chart for prodms system deploying. Contains all microservices.
type: application
version: 1.0.0-SNAPSHOT
appVersion: "1.0.0-SNAPSHOT"

dependencies:
  - name: archive
    version: 1.0.0-SNAPSHOT
    condition: archiveEnabled
    repository: "https://yuryklimchuk.github.io/prodms-helm"

  - name: warehouse
    version: 1.0.0-SNAPSHOT
    condition: warehouseEnabled
    repository: "https://yuryklimchuk.github.io/prodms-helm"

  - name: files
    version: 1.0.0-SNAPSHOT
    condition: filesEnabled
    repository: "https://yuryklimchuk.github.io/prodms-helm"
