basicEnabled: true
basic:
  replicaCount: 1
  
  image:
    repository: "docker.io"
    tag: "prodms/warehouse"
    version: "1.0.0-SNAPSHOT"
    pullPolicy: IfNotPresent
  
  app:
    id: "warehouse"
    port: 8080

kafka:
  url: "prodms-kafka-cluster-kafka-bootstrap.prodms-infra:9092"
mongo:
  connection:
    host: "prodms-mongodb-svc.prodms-infra"
